name: pre-commit hooks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout alembic_utils
      uses: actions/checkout@v2

    - name: set up python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit


    - name: run pre-commit hooks
      run: |
        pre-commit run --all-files
